services:
  - name: task-manager-backend
    type: web
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 4000
